[package]
name = "rust-eigenda-signers"
repository = "https://github.com/Layr-Labs/eigenda-client-rs"
version = "0.1.4"
authors.workspace = true
description = "EigenDA Signers"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
secp256k1 = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
